### PR TITLE
Fix exported types

### PR DESCRIPTION
**Pull request by jsdevtom**
Full credit to @dderjoel :tada: 

Ps @dderjoel, please confirm you are happy with the changes

### CODE REVIEW

**Comment by jsdevtom** [comment]
closes #2

**Comment by dderjoel** [comment]
Well, so I cannot fully confirm since the package is not in the npm registry yet. 
However, if I clone the repo again, run `npm i` and `npm run dist`, I see the `dist` directory containing `lib` and in there i see the typings `truegin.d.ts`. However, in the latest `package.json` It is still referenced to `dist/types/truegin.d.ts` which does not exist. 

It seems, that this [commit](https://github.com/jsdevtom/truegin/pull/6/commits/94e3332014915089d8cd7abeb77da5ee062b027c) was somehow skipped, or I checkout out the wrong branch. (even this branch `fixExportedTypes` has the wrong links in `main` and `module`.) But the dependencies should not be downgraded, as they would by this commit.

**Comment by dderjoel** [comment]
I have had another look at the branch `fixExportTypes`. I think the order was mixed up and the commit https://github.com/jsdevtom/truegin/commit/bc548b2bdd5343c9779baf093334041ceac42a4d should be removed from the branch so that the paths in `package.json` direct to the lib-sub directory.

**Comment by jsdevtom** [comment]
I have removed bc548b2. Does that solve the issue?

**Comment by dderjoel** [comment]
Yes, it did! Thanks!
Will you push a new version to the npm-registry?

**Comment by jsdevtom** [comment]
Awesome!

The release is automated upon merging in to master if significant changes have occurred (which in this case they have):

> semantic-release is meant to be executed on the CI environment after every successful build on the release branch. This way no human is directly involved in the release process and the releases are guaranteed to be unromantic and unsentimental.

- [semantic-release](https://github.com/semantic-release/semantic-release#automation-with-ci)

**Comment by dderjoel** [comment]
fantastic!

**Pull request merged**
